mlflow_config:
  tracking_uri: "mlruns" 
  experiment_name: "MLOps Library Demo"

model_params:
  classification:
    C: 1.0
    solver: "liblinear"
  regression:
    fit_intercept: True
  clustering:
    n_clusters: 3
    init: "k-means++"
  deep_learning:
    epochs: 5
    batch_size: 32